version: '3'

vars:
  MODULE: github.com/masegraye/connect-plugin-go

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install-deps:
    desc: Install required build dependencies
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
      - go install ./cmd/protoc-gen-connect-plugin
    status:
      - which protoc-gen-go
      - which protoc-gen-connect-go
      - which protoc-gen-connect-plugin

  proto:
    desc: Generate protobuf code for core and examples
    deps: [install-deps]
    cmds:
      - mkdir -p gen/connectplugin/v1
      - mkdir -p examples/kv/gen/kv/v1
      # Core plugin protocol (no delegate generation - internal framework)
      - protoc --proto_path=proto
          --go_out=gen
          --go_opt=paths=source_relative
          --connect-go_out=gen
          --connect-go_opt=paths=source_relative
          proto/plugin/v1/handshake.proto
          proto/plugin/v1/health.proto
          proto/plugin/v1/broker.proto
          proto/plugin/v1/registry.proto
          proto/plugin/v1/lifecycle.proto
          proto/plugin/v1/plugininfo.proto
      # Logger capability (with delegate generation for user-facing API)
      - protoc --proto_path=proto
          --go_out=gen
          --go_opt=paths=source_relative
          --connect-go_out=gen
          --connect-go_opt=paths=source_relative
          --connect-plugin_out=gen
          --connect-plugin_opt=paths=source_relative
          proto/capability/logger/v1/logger.proto
      # KV example (with delegate generation)
      - protoc --proto_path=examples/kv/proto
          --go_out=examples/kv/gen
          --go_opt=paths=source_relative
          --connect-go_out=examples/kv/gen
          --connect-go_opt=paths=source_relative
          --connect-plugin_out=examples/kv/gen
          --connect-plugin_opt=paths=source_relative
          examples/kv/proto/kv.proto

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  build:
    desc: Build the library
    deps: [proto]
    cmds:
      - go build ./...
      - go mod tidy

  test:
    desc: Run unit tests (excludes integration tests)
    deps: [proto]
    cmds:
      - go test -v -short ./...

  test:unit:
    desc: Run unit tests only (alias for test)
    deps: [proto]
    cmds:
      - go test -v -short ./...

  test:security:
    desc: Run security-specific tests (timing, auth, validation, expiration)
    deps: [proto]
    cmds:
      - go test -v -short -run "TestTimingAttack|TestCryptoErrors|TestAuthBypass|TestTLSWarnings|TestHandshake|TestTokenExpiration|TestServiceAuthorization|TestValidate|TestTokenBucket" ./...

  test:integration:
    desc: Run Phase 2 integration tests with real plugin processes
    deps: [build-examples]
    cmds:
      - go test -v -run TestIntegration_ -timeout 60s

  test:all:
    desc: Run all tests (unit + integration)
    deps: [build-examples]
    cmds:
      - go test -v -timeout 60s ./...

  test:coverage:
    desc: Run tests with coverage report
    deps: [proto]
    cmds:
      - go test -v -short -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:coverage:full:
    desc: Run all tests with coverage (unit + integration)
    deps: [build-examples]
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Full coverage report generated at coverage.html"

  test:bench:
    desc: Run benchmark tests
    deps: [proto]
    cmds:
      - go test -bench=. -benchmem ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - gofmt -s -w .
      - goimports -w .

  check:
    desc: Run all checks (fmt, lint, test)
    cmds:
      - task: fmt
      - task: lint
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f coverage.out coverage.html
      - rm -rf gen
      - rm -rf examples/kv/gen
      - rm -rf dist
      - rm -f examples/logger-plugin/logger-plugin
      - rm -f examples/cache-plugin/cache-plugin
      - rm -f examples/app-plugin/app-plugin
      - go clean ./...

  build-examples:
    desc: Build example binaries to dist/
    deps: [proto]
    cmds:
      - mkdir -p dist
      - go build -o dist/kv-server ./examples/kv/server
      - go build -o dist/kv-host ./examples/kv/host
      - go build -o dist/kv-host-watch ./examples/kv/host-watch
      - go build -o dist/kv-integ-fx ./examples/kv/integ-fx
      - go build -o dist/logger-plugin ./examples/logger-plugin
      - go build -o dist/cache-plugin ./examples/cache-plugin
      - go build -o dist/app-plugin ./examples/app-plugin
      - go build -o dist/storage-plugin ./examples/storage-plugin
      - go build -o dist/api-plugin ./examples/api-plugin
      - go build -o dist/platform-host ./examples/docker-compose/host
      - go build -o dist/url-client ./examples/url-client
      - go build -o dist/fx-managed ./examples/fx-managed

  # Manual example runners (for development)
  example:server:
    desc: Run KV plugin server manually
    deps: [build-examples]
    cmds:
      - ./dist/kv-server

  example:client:
    desc: Run KV client manually (requires server)
    deps: [build-examples]
    cmds:
      - ./dist/kv-host

  example:watch:
    desc: Run KV Watch client manually (requires server)
    deps: [build-examples]
    cmds:
      - ./dist/kv-host-watch

  example:fx-managed:
    desc: Run fx-managed example (unmanaged deployment with fx)
    deps: [build-examples]
    cmds:
      - ./dist/fx-managed

  # Integration tests
  integ:kv:test:
    desc: Integration test - KV with fx (in-process server/client)
    deps: [build-examples]
    env:
      CONNECTPLUGIN_DISABLE_TLS_WARNING: "1"
    cmds:
      - ./dist/kv-integ-fx

  integ:kv-standalone:test:
    desc: Integration test - KV server/client (separate processes)
    deps: [build-examples]
    env:
      CONNECTPLUGIN_DISABLE_TLS_WARNING: "1"
    cmds:
      - |
        PORT=18080 ./dist/kv-server &
        SERVER_PID=$!
        sleep 1
        PLUGIN_ENDPOINT=http://localhost:18080 ./dist/kv-host
        EXIT_CODE=$?
        kill $SERVER_PID 2>/dev/null || true
        exit $EXIT_CODE

  integ:kv-watch:test:
    desc: Integration test - KV Watch streaming
    deps: [build-examples]
    env:
      CONNECTPLUGIN_DISABLE_TLS_WARNING: "1"
    cmds:
      - |
        PORT=18080 ./dist/kv-server &
        SERVER_PID=$!
        sleep 1
        PLUGIN_ENDPOINT=http://localhost:18080 ./dist/kv-host-watch
        EXIT_CODE=$?
        kill $SERVER_PID 2>/dev/null || true
        exit $EXIT_CODE

  integ:fx-managed:test:
    desc: Integration test - mixed strategies (in-memory + process plugins)
    deps: [build-examples]
    env:
      CONNECTPLUGIN_DISABLE_TLS_WARNING: "1"
    cmds:
      - timeout 30 ./dist/fx-managed || true

  integ:all:
    desc: Run all integration tests
    cmds:
      - task: integ:kv:test
      - task: integ:kv-standalone:test
      - task: integ:kv-watch:test
      - task: integ:fx-managed:test

  # Documentation tasks
  docs:serve:
    desc: Serve documentation locally with MkDocs
    deps: [docs:install]
    cmds:
      - python3 -m mkdocs serve

  docs:build:
    desc: Build documentation static site
    deps: [docs:install]
    cmds:
      - python3 -m mkdocs build

  docs:deploy:
    desc: Deploy documentation to GitHub Pages
    deps: [docs:install]
    cmds:
      - python3 -m mkdocs gh-deploy

  docs:install:
    desc: Install MkDocs and dependencies
    cmds:
      - python3 -m pip install -r requirements.txt
    status:
      - python3 -c "import mkdocs" 2>/dev/null
