version: '3'

vars:
  MODULE: github.com/example/connect-plugin-go

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install-deps:
    desc: Install required build dependencies
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
    status:
      - which protoc-gen-go
      - which protoc-gen-connect-go

  proto:
    desc: Generate protobuf code for examples
    deps: [install-deps]
    cmds:
      - mkdir -p examples/kv/gen/kv/v1
      - protoc --proto_path=examples/kv/proto
          --go_out=examples/kv/gen
          --go_opt=paths=source_relative
          --connect-go_out=examples/kv/gen
          --connect-go_opt=paths=source_relative
          examples/kv/proto/kv.proto

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  build:
    desc: Build the library
    deps: [proto, tidy]
    cmds:
      - go build ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - gofmt -s -w .
      - goimports -w .

  check:
    desc: Run all checks (fmt, lint, test)
    cmds:
      - task: fmt
      - task: lint
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f coverage.out coverage.html
      - rm -rf examples/kv/gen
      - rm -rf dist
      - go clean ./...

  build-examples:
    desc: Build example binaries to dist/
    deps: [proto]
    cmds:
      - mkdir -p dist
      - go build -o dist/kv-server ./examples/kv/server
      - go build -o dist/kv-host ./examples/kv/host

  example-server:
    desc: Build and run KV plugin server
    deps: [build-examples]
    cmds:
      - ./dist/kv-server

  example-client:
    desc: Run KV plugin client (requires server running)
    deps: [build-examples]
    cmds:
      - ./dist/kv-host

  # Integration tests
  integ:kv:server:
    desc: Run KV plugin server for integration testing
    deps: [build-examples]
    cmds:
      - ./dist/kv-server

  integ:kv:client:
    desc: Run KV plugin client (requires integ:kv:server running)
    deps: [build-examples]
    cmds:
      - ./dist/kv-host

  integ:kv:test:
    desc: Integration test - run server and client together
    deps: [build-examples]
    cmds:
      - |
        # Start server in background
        ./dist/kv-server &
        SERVER_PID=$!

        # Wait for server to start
        sleep 1

        # Run client
        ./dist/kv-host
        CLIENT_EXIT=$?

        # Kill server
        kill $SERVER_PID 2>/dev/null || true

        # Exit with client's exit code
        exit $CLIENT_EXIT

  integ:all:
    desc: Run all integration tests
    cmds:
      - task: integ:kv:test
